* Cron: краткая история, популярные версии, использование и устройство

** Происхождение видов

   Периодическое выполнение пользовательских или системных программ - очевидная необходимость во
   всех операционных системах. Поэтому необходимость в сервисах, позволяющих централизованно
   планировать и выполнять такие работы, осозналась программистами очень рано.

   Unix-подобные операционные системы ведут свою родословную от [[https://en.wikipedia.org/wiki/Version_7_Unix][Version 7 Unix]], разработанного в
   70-х годах прошлого века в [[https://en.wikipedia.org/wiki/Bell_Labs][Bell Labs]]. Эта операционная система стала прародителем двух крупных
   семейств ОС: BSD-подобных и SysV-подобных. Вместе c Version 7 Unix поставлялся и сервис cron,
   позволявший регулярно выполнять задачи суперпользователя.

   Типичный современный cron - несложная программа, но алгоритм работы оригинального варианта был
   совсем простым: сервис просыпался раз в минуту, читал табличку с задачами из единственного файл
   (/etc/lib/crontab), и выполнял для суперпользователя те задачи, которые надо было выполнить в
   текущую минуту.

   Сервис оказался одновременно простым и очень полезным, поэтому со всеми последующими
   Unix-подобными операционными системами поставлялись те или иные варианты cron с похожим - но
   усовершенствованным - интерфейсом.

   Обобщенное описание формата crontab и базовых принципов работы утилиты было включено уже во
   второе издание главного стандарта Unix-подобных операционных систем - [[https://en.wikipedia.org/wiki/POSIX][POSIX]] - и, таким образом,
   cron из стандарта де-факто стал стандартом де-юре.

   В 1987 году Пол Викси (англ. [[https://en.wikipedia.org/wiki/Paul_Vixie][Paul Vixie]]), опросив пользователей Unix на предмет пожеланий к cron,
   выпустил свою версию демона, которая исправляла ключевые проблемы традиционных cron и расширила
   стандартный синтаксис файлов-табличек.

   У Vixie Cron была очень либеральная лицензия, верней, вообще никакой лицензии помимо пожеланий в
   README: гарантий автор не дает, имя автора удалять нельзя, а продавать программу можно только
   вместе с исходным кодом. Эти требования совместимы с принципами набирающего в те годы
   популярность свободного ПО, поэтому некоторые ключевые из появившихся в начале 90-х дистрибутивов
   Linux взяли Vixie Cron в качестве системного cron и развивают его до сих пор.

   В частности, RedHat и Suse развивают форк Vixie Cron - cronie; а Debian (а вместе с ним и Ubuntu)
   используют фактически оригинальное издание Vixie Cron с небольшими патчами.

   Давайте для начала познакомимся с описанной в POSIX стандартной утилитой crontab, после чего
   разберем Vixie Cron и специфичные для популярных дистрибутивов версии.

** TODO POSIX Crontab
** TODO Хит продаж - Vixie Cron
** TODO Vixie Cron в Debian и Ubuntu
** TODO Vixie Cron в RedHat, Fedora и CentOS
** TODO Устройство Vixie Cron
** TODO Альтернативы
