* Cron: история, популярные версии, использование и устройство
** TODO Аннотация

   TODO: Сослаться на статью Алексея.
   TODO: красивая цитата
   TODO: BI и старые юниксовые утилиты

** TODO Содержание

** Происхождение видов

   Периодическое выполнение пользовательских или системных программ - очевидная необходимость во
   всех операционных системах. Поэтому необходимость в сервисах, позволяющих централизованно
   планировать и выполнять такие работы, осозналась программистами очень рано.

   Unix-подобные операционные системы ведут свою родословную от [[https://en.wikipedia.org/wiki/Version_7_Unix][Version 7 Unix]], разработанного в
   70-х годах прошлого века в [[https://en.wikipedia.org/wiki/Bell_Labs][Bell Labs]] в том числе и знаменитым Кеном Томпсоном (англ. [[https://en.wikipedia.org/wiki/Ken_Thompson][Ken
   Thompson]]). Эта операционная система стала прародителем двух крупных семейств ОС: BSD-подобных и
   SysV-подобных. Вместе c Version 7 Unix поставлялся и сервис cron, позволявший регулярно выполнять
   задачи суперпользователя.

   Типичный современный cron - несложная программа, но алгоритм работы оригинального варианта был
   совсем простым: сервис просыпался раз в минуту, читал табличку с задачами из единственного файл
   (/etc/lib/crontab), и выполнял для суперпользователя те задачи, которые надо было выполнить в
   текущую минуту.

   Сервис оказался одновременно простым и очень полезным, поэтому со всеми последующими
   Unix-подобными операционными системами поставлялись те или иные варианты cron с похожим - но
   усовершенствованным - интерфейсом.

   Обобщенное описание формата crontab и базовых принципов работы утилиты в 92-ом году было включено
   в главный стандарт Unix-подобных операционных систем - [[https://en.wikipedia.org/wiki/POSIX][POSIX]] - и, таким образом, cron из
   стандарта де-факто стал стандартом де-юре.

   В 1987 году Пол Викси (англ. [[https://en.wikipedia.org/wiki/Paul_Vixie][Paul Vixie]]), опросив пользователей Unix на предмет пожеланий к cron,
   выпустил свою версию демона, которая исправляла ключевые проблемы традиционных cron и расширила
   синтаксис файлов-таблиц.

   Vixie cron к 3-ей версии стал отвечать требованиям POSIX, к тому же у программы была либеральная
   лицензия, верней, вообще никакой лицензии, если не считать пожеланий в README: гарантий автор не
   дает, имя автора удалять нельзя, а продавать программу можно только вместе с исходным кодом. Эти
   требования оказались совместимы с принципами набиравшего в те годы популярность свободного ПО,
   поэтому некоторые ключевые из появившихся в начале 90-х дистрибутивов Linux взяли Vixie cron в
   качестве системного cron и развивают его до сих пор.

   В частности, RedHat и Suse развивают форк Vixie cron - cronie; а Debian (и Ubuntu) используют
   оригинальное издание Vixie cron со множеством патчей.

   Давайте для начала познакомимся с описанной в POSIX стандартной утилитой crontab, после чего
   разберем расширения Vixie cron и использование вариантов Vixie cron в популярных дистрибутивах.
   И, наконец, вишенка на торте - подробный разбор устройства демона cron.

** POSIX crontab

   Если оригинальный cron всегда работал для суперпользователя, то современные планировщики имеют
   дело с задачами обычных пользователей - так безопасней и удобней.

   Cron-ы обычно поставляются двумя программами: постоянно работающий суперпользовательский демон
   cron и доступная пользователям программа crontab. Последняя позволяет редактировать таблички
   задач, специфичные для каждого пользователя в системе.

   В [[https://www.unix.com/man-page/POSIX/1posix/crontab/][стандарте POSIX]] никак не описывается поведение демона и формализована только пользовательская
   программа [[https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html][crontab]]. Существование каких-либо механизмов запуска пользовательских задач, конечно,
   подразумевается, но не описано подробно.

   Вызовами стандартного crontab можно сделать только четыре вещи: отредактировать пользовательскую
   таблицу задач в редакторе, загрузить таблицу из файла, показать текущую таблицу задач и очистить
   таблицу задач. С точки зрения пользователя для запуска задач больше ничего не требуется.

   Примеры работы утилиты crontab:

   #+BEGIN_SRC shell
   crontab -e # редактировать таблицу задач
   crontab -l # показать таблицу задач
   crontab -r # удалить таблицу задач
   crontab path/to/file.crontab # загрузить таблицу задач из файла
   #+END_SRC

   При вызове =crontab -e= будет использоваться редактор, указанный в стандартной переменной окружения
   =EDITOR=.

   Сами задачи описаны в следующем формате:

   #+BEGIN_SRC crontab
   # строки-комментарии игнорируются
   #
   # задача, выполняемая ежеминутно
   * * * * * /path/to/exec -a -b -c
   # задача, выполняемая на 10-ой минуте каждого часа
   10 * * * * /path/to/exec -a -b -c
   # задача, выполняемая на 10-ой минуте 2-ого часа каждого дня и использующая перенаправление стандартного потока вывода
   10 2 * * * /path/to/exec -a -b -c > /tmp/cron-job-output.log
   #+END_SRC

   Первые пять полей записей: минуты [1..60], часы [0..23], дни месяца [1..31], месяцы [1..12], дни
   недели [0..6], где 0 - воскресение. Последнее, шестое, поле - строка, которая будет выполнена
   стандартным интерпретатором команд.

   В первых пяти полях значения можно перечислять через запятую:

   #+BEGIN_SRC crontab
   # задача, выполняемая в 1-ую и 10-ую минуты каждого часа
   1,10 * * * * /path/to/exec -a -b -c
   #+END_SRC

   Или через дефис:

   #+BEGIN_SRC crontab
   # задача, выполняемая в каждую из первых 10-и минут каждого часа
   0-9 * * * * /path/to/exec -a -b -c
   #+END_SRC

   Доступ пользователей к планированию задач регулируется в POSIX файлам cron.allow и cron.deny в
   которых перечисляются, соответственно, пользователи с доступом к crontab и пользователи без
   доступа к программе. Расположение этих файлов стандарт никак не регламентирует.

   Запускаемым программам согласно стандарту должны передаваться по меньшей мере четыре переменные
   окружения:

   1. HOME - домашняя директория пользователя.
   2. LOGNAME - логин пользователя.
   3. PATH - путь, по которому можно найти стандартные утилиты системы.
   4. SHELL - путь к использованному командному интерпретатору.

   Примечательно, что POSIX ничего не говорит о том, откуда берутся значения для этих переменных.

** Хит продаж - Vixie cron 3.0pl1

   Общий предок популярных вариантов cron - Vixie cron 3.0pl1, опубликованный в comp.sources.unix.
   Основные возможности этой версии мы и рассмотрим подробней.

   Vixie cron поставляется в двух программах (cron и crontab). Демон cron отвечает за чтение и
   запуск задач из системной таблицы задач и таблиц задач отдельных пользователей. Утилита crontab -
   за редактирование пользовательских таблиц.

*** Таблиц задач и файлы конфигурации

    Таблица задач суперпользователя расположена в /etc/crontab. Синтаксис системной таблицы имеют
    общий для Vixie cron синтаксис с поправкой на то, что в ней шестой колонкой указывается имя
    пользоваеля, от которого запускается задача:

    #+BEGIN_SRC crontab
    # Запускается ежеминутно от пользователя vlad
    * * * * * * vlad /path/to/exec
    #+END_SRC

    Таблицы задач обычных пользователей располагаются в /var/cron/tabs/username и используют общий
    синтаксис. При запуске утилиты crontab от имени пользователя редактируются именно эти файлы.

    Управление списками пользователей, имеющих доступ к crontab, происходит в файлах //var/cron/allow
    и //var/cron/deny/, куда достаточно внести имя пользователя отдельной строкой.

*** Расширенный синтаксис

   По сравнению с POSIX crontab Пол Викси добавил несколько очень полезных модицикаций в синтаксис
   таблиц задач утилиты.

   Стал доступен расширенный синтаксис таблиц, например, можно указывать дни недели или месяцы
   поименно (Mon, Tue и так далее):

   #+BEGIN_SRC crontab
   # Запускается ежеминутно по понедельникам и вторникам в январе
   * * * Jan Mon,Tue * /path/to/exec
   #+END_SRC

   Можно указывать шаг, через который запускаются задачи:

   #+BEGIN_SRC crontab
   # Запускается каждую вторую минуту
   */2 * * * Mon,Tue /path/to/exec
   #+END_SRC

   Шаги и интервалы можно смешивать:

   #+BEGIN_SRC crontab
   # Запускается каждую вторую минуту первых десяти минут каждого часа
   0-10/2 * * * * * /path/to/exec
   #+END_SRC

   Поддерживаются интуитивные альтернативы обычному синтаксису: reboot, yearly, annually, monthly,
   weekly, daily, midnight, hourly:

   #+BEGIN_SRC crontab
   # Запускается после перезагрузки системы
   @reboot /exec/on/reboot
   # Запускается раз в день
   @daily /exec/daily
   # Запускается раз в час
   @hourly /exec/daily
   #+END_SRC

*** Среда выполнения задач

   Vixie cron позволяет менять окружение запускаемых приложений.

   Изначально переменные окружения USER, LOGNAME и HOME не просто предоставляются демоном, а берутся
   по умолчанию из файла [[https://en.wikipedia.org/wiki/Passwd][passwd]]. Переменная PATH по умолчанию получает значение "/usr/bin:/bin/", а
   SHELL - "/bin/sh". Значения всех переменных кроме LOGNAME можно изменить в таблицах
   пользователей.

   Некоторые переменные окружения (прежде всего SHELL и HOME) используются самим cron для запуска
   задачи. Вот как может выглядеть использование bash вместо стандартного sh для запуска
   пользовательских задач:

   #+BEGIN_SRC crontab
   SHELL=/bin/bash
   HOME=/tmp/
   # exec будет запущен bash-ем в /tmp/
   * * * * * /path/to/exec
   #+END_SRC

   В конечном итоге все определенные в таблице переменные окружения (используемые cron или
   необходимые процессу) будут переданы запущенной задаче.

   Для редактирования файлов утилитой crontab используется редактор указанный в переменных окружения
   VISUAL или EDITOR. Если в среде, где был запущен crontab, эти переменные не определены, то
   используется "/usr/ucb/vi".

** cron в Debian и Ubuntu

   Разработчики Debian и производных дистрибутивов [[https://salsa.debian.org/debian/cron][сильно модифицированную версию]] Vixie cron 3.0pl1.
   Отличий в синтаксисе файлов-таблиц нет, с точки зрения пользователей это тот же самый Vixie cron.
   Крупнейшие новые возможности: поддержка [[https://en.wikipedia.org/wiki/Syslog][syslog]], [[https://en.m.wikipedia.org/wiki/Security-Enhanced_Linux][SELinux]] и [[https://en.wikipedia.org/wiki/Linux_PAM][PAM]].

   Из менее трудозатратных, но осязаемых изменений - расположение ключевых конфигурационных файлов и
   таблиц задач.

   Пользовательские таблицы в Debian располагаются в директории /var/spool/cron/crontabs, системная
   таблица все там же - в /etc/crontab. Специфичные для пакетов Debian таблицы задач теперь
   помещаются в //etc/cron.d/, откуда демон cron их автоматически считывает. Управление доступом
   пользователей регулируется в файлах /etc/cron.allow и /etc/cron.deny.

   В качестве командной оболочки по умолчанию по-прежнему используется //bin/sh/, в роли которыго в
   Debian выступает небольшой POSIX-совместимый шелл [[http://man7.org/linux/man-pages/man1/dash.1.html][dash]], запущенный без чтения какой-либо
   конфиграции (в неинтерактивном режиме).

   Сам cron в последних версиях Debian запускается через systemd, а конфигурацию запуска можно
   посмотреть в /lib/systemd/system/cron.service. Ничего особенного в конфигурации сервиса нет,
   любое более тонкое управление задачами возможно сделать через переменные окружения, объявленные
   прямо в crontab-ах каждого из пользователей.

** cronie в RedHat, Fedora и CentOS

   [[https://github.com/cronie-crond/cronie][Cronie]] - форк Vixie cron версии 4.1. Как и в Debian синтаксис не менялся, но добавлена поддержка
   PAM и SELinux, работы в кластере, слежение за файлами при помощи inotify и других новых
   возможностей.

   Конфигурация по умолчанию находится в обычных местах: системная таблица в /etc/crontab, пакеты
   помещают свои таблицы в /etc/cron.d/, пользовательские таблицы попадают в /var/spool/cron/crontabs.

   Демон запускается под управлением systemd, конфигурация сервиса -
   /lib/systemd/system/crond.service.

   В Redhat-подобных дистрибутивах при запуске по умолчанию используется /bin/sh, в роли которого
   выступает стандартный bash. Надо заметить, что при запуске задач cron через /bin/sh командная
   оболочка bash запускается в POSIX-совместимом режиме, и *не читает* никакой дополнительной
   конфигурации - работает в неинтерактивном режиме.

** TODO Устройство Vixie cron

   TODO: original once per minute -> williams -> once per minute again (cronie and inotify?)
   TODO: job collection into a unified table
   TODO: main loop and time correction
   TODO: job launch procedure
   TODO: @reboot
   TODO: pid

   Современные потомки cron по сравнению с Vixie cron не изменились радикально, но все же
   представляют множество новых возможностей, которые рядовому пользователю не понадобится. Многие
   из этих расширений оформлены неаккуратно и путают код. В то же время оригинальный исходный код
   cron в исполнении Пола Викси же читать - одно удовольствие.

   Поэтому разбор устройства cron я решил провести на примере общей для обоих ветвей развития
   программы - Vixie cron 3.0pl1.

** TODO Выводы

   TODO: альтернативы

   TODO: указать, что надо обращаться к документации каждой из платформ
